apiVersion: v1
kind: EcosystemResource
metadata:
  name: neo4j-movies
  labels:
    cto.hume.io/tier: core
spec:
  fqn: Hume.Orchestra.Resource.Neo4j
  parameters:
    - name: host
      value: neo4j
    - name: port
      value: 7687
    - name: user
      value: neo4j
    - name: password
      value: '$INIT_DB_PASSWORD'
    - name: database
      value: movies