apiVersion: v1
kind: KnowledgeGraph
metadata:
  name: 'cto demo kg'
  labels:
    cto.hume.io/tier: core
spec:
  label: CTO Demo KG
  perspectives:
    - full-perspective
  workflows:
    - workflow-neo4j-basic
  actions:
    - movies-create-graph
    - movies-show-matrix-actors
  schema:
    classes:
      - label: Movie
        color: '#6200EA'
        icon: mdi-movie
        attributes:
          - label: title
            type: STRING
            full_text: true
          - label: released
            type: INTEGER
      - label: Person
        color: '#26A69A'
        icon: person
        attributes:
          - label: name
            type: STRING
            full_text: true
      - label: Genre
        color: '#26A69A'
        icon: mdi-label
        attributes:
          - label: name
            type: STRING
            full_text: true
    relationships:
      - label: ACTED_IN
        start: Person
        end: Movie
      - label: HAS_GENRE
        start: Movie
        end: Genre